### ISSUE TITLE
Update Routine - Gedankenspielerei

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/docker-redaxo#24]
Ich überlege seit ein paar Tagen, ob wir der Installationsroutine mitgeben können, dass sie gegebenenfalls ein Update vom Core macht. @bloep rein prinzipiell wäre das über die Konsole möglich oder?

@schuer aktuell wird geprüft, ob das www Verzeichnis leer ist. Ist es das, wird installiert. Wenn es das nicht ist, steigt das Script aus und startet den Apache. Wenn man an der Stelle nun raus kriegen würde, welche Redaxo Version installiert ist und welche Version über die docker-compose definiert ist, könnte das doch klappen. 

Was meint ihr? Brauchbare/umsetzbare Idee?

**Comment by schuer** [comment]
@pschuchmann Das wäre sicherlich an manchen Stellen nützlich, allerdings würde man damit auch sehr stark in die App-Ebene reingreifen. Aus meiner Sicht zu stark, denn ich würde REDAXO-Updates lieber gezielt manuell handhaben wollen, nicht automatisiert. Docker sollte eigentlich eher nur die Umgebung bedienen und bereitstellen. My 2 cents.

**Comment by pschuchmann** [comment]
Ja, das stimmt wohl. Gegensteuern könnte man bei sowas ja indem man die Version explizit angibt, bzw. bei älteren vorhandenen Versionen nur bis zu der angegebenen Version ein Update ausführt.

`image: friendsofredaxo/redaxo:5.11.0`

Andererseits kam mir auch gerade in den Sinn, dass es bei einigen Versionen auch Probleme beim Update gab, wenn die Ausgangsversion zu niedrig war. Mal sehen, was Marcel sagt.

Ist wie der Titel sagt bisher nur Gedankenspielerei :D

**Comment by bloep** [comment]
Ich bin da eher bei Dirk, Docker sollte IMHO die Umgebung bereitstellen, aber nicht die Installation managen mit Updates und co. 
Zudem denke ich, dass es einen höheren Aufwand mit sich bringt, dass in Zukunft up-to-date zu halten.

**Comment by pschuchmann** [comment]
Ok, dann bleibt es eine Gedankenspielerei 😊 Danke für euren Input!
