### ISSUE TITLE
implement TravisCI tests

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/docker-redaxo#5]

**Comment by bloep** [comment]
kurze Frage, wofür möchtest du travis checks haben?

**Comment by schuer** [comment]
In erster Linie, um zu schauen, ob aus den Images Container gebaut und gestartet werden können, oder ob dabei Fehler fliegen. Wenn man es weiter treibt, könnte man noch rasch testen, ob auch REDAXO richtig installiert wird.

**Comment by bloep** [comment]
> In erster Linie, um zu schauen, ob aus den Images Container gebaut

macht das nicht schon die Docker Hub Pipeline ?

Edit:
Ah, ist hier gar net aktiviert. Kannste in den Build Options bei Docker Hub aktivieren
![image](https://user-images.githubusercontent.com/21292755/73680588-cc15d400-46bc-11ea-8119-003aeceb2967.png)

**Comment by schuer** [comment]
@bloep Sorry, hab ganz verpasst zu antworten. Ich bin nicht so richtig im Thema, wie man sinnvoll Docker-Images testet.

Du hast voll recht, Docker Hub kann das mit seiner Infrastruktur. Aber es gab irgendwelche Gründe, warum viele prominente Images TravisCI nutzen… dunno. Werde mich mal schlau machen bei Gelegenheit.

**Comment by schuer** [comment]
Der Docker Hub kann das inzwischen wirklich gut selbst, so dass Travis in der Tat nicht mehr von uns benötigt wird.

Dass noch immer viele prominente Images Travis nutzen, liegt vermutlich daran, dass der Docker Hub vor einiger Zeit noch keine Pull Requests testen und an Github reporten konnte, siehe https://medium.com/vaidikkapoor/managing-open-source-docker-images-on-docker-hub-using-travis-7fd33bc96d65 (Mid 2018).
