### ISSUE TITLE
REDAXO 5.16.0 Beta ergänzen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/docker-redaxo#79]
Eine erste Beta-Version wurde eben veröffentlicht: https://github.com/redaxo/redaxo/releases/tag/5.16.0-beta1

Vielleicht hat jemand Lust, das Docker-Image damit auszustatten? Das geht so:

1. In der README den Abschnitt lesen: »[REDAXO oder PHP aktualisieren](https://github.com/FriendsOfREDAXO/docker-redaxo/blob/main/README-developers.md#redaxo-oder-php-aktualisieren)«
2. Projekt forken oder einen neuen Branch anlegen
3. Die Angaben für die neue REDAXO-Beta in [/source/images.yml](https://github.com/FriendsOfREDAXO/docker-redaxo/blob/main/source/images.yml) aktualisieren. Weil es eine Beta-Version ist, statten wir nur das **Edge**-Image (unten) damit aus, nicht das **Stable**-Image (oben). Am Anfang der Datei steht, wie man mittels Curl den Hashwert ermittelt.
4. Einen Pull Request starten
5. Abwarten, bis die automatischen Tests durchgelaufen sind und um Review bitten

Sobald gemerged worden ist, sind 15-20 Minuten später die Images im Docker Hub und bei GitHub verfügbar. 🐳

**Comment by thorol** [comment]
@schuer übernehme ich.

**Comment by schuer** [comment]
https://github.com/FriendsOfREDAXO/docker-redaxo/pull/81

Danke @thorol!
